apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: tequipy
  labels:
    app.kubernetes.io/name: tequipy
    app.kubernetes.io/component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tequipy
      app.kubernetes.io/component: backend
